### PR TITLE
Remove unused files

### PR DESCRIPTION
**Pull request by stephendonner**
Should address https://github.com/mozilla/mozwebqa-dashboard/issues/55

@davehunt r?

### CODE REVIEW

**Comment by davehunt** [comment]
Let's see if @justinpotts has time to confirm that removing these files is safe.

**Comment by stephendonner** [comment]
Sounds prudent - good idea!

**Comment by justinpotts** [comment]
Lgtm! r+

liftoff

**Comment by stephendonner** [comment]
Thx, you two!

**Comment by davehunt** [comment]
So it appears this totally broke the dashboard and we didn't notice for almost two weeks. I'll work to restore the necessary files.

**Pull request merged**
